KAS:
  client:
    accessKeyId: ENC(0CSiy4T32SzeaM6fSyW8DLbRkZHkPzw8hQqKF8eF0e+x8bAkKGGj0Q==)
    secretAccessKey: ENC(8Wbtgz8yT52X22wUPNwQYGxsCCmRN558cL+x1Ge5TjvChF/7zRDz1EIcn96IQ+Vq+2vexS3uOU4=)
    authorization: ENC(nvjLwcTiTURlSX6Lpc3GBHGEClRDl8U0cxzdEK/p3mPaEpZpY87TVfv6hMy059xGhFDovUj5jWJClUVp56d1GrriyCu0Joc3VWVbUzUqTtpbu/2wy1eSdxqqFEkKt9xhu8xOzbrsT4Y=)
    contract-alias: "unijoa"